# Generated by Django 5.2.3 on 2025-07-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
