// English translations
export const en = {
	main_title: "TAJIKISTAN",
	main_subtitle: "LAND OF",
	main_description: "ANCIENT CULTURES",
	discover_title: "Discover Tajikistan",
	discover_subtitle: "A land of breathtaking mountains, crystal-clear lakes, and rich cultural heritage",
	about_mountains: "Majestic Mountains",
	about_mountains_desc: "Home to the Pamir Mountains, known as the 'Roof of the World', with peaks reaching over 7,000 meters.",
	about_nature: "Natural Beauty",
	about_nature_desc: "From the turquoise waters of Iskanderkul to the vast alpine meadows, nature's beauty is everywhere.",
	about_culture: "Ancient Culture",
	about_culture_desc: "Centuries-old traditions, vibrant bazaars, and warm hospitality define Tajik culture.",
	map_title: "Map of Tajikistan",
	destinations_title: "Popular Destinations",
	destinations_subtitle: "Explore the most beautiful places in Tajikistan",
	categories_title: "Explore by Category",
	categories_subtitle: "Find your perfect adventure",
	cat_mountains: "Mountains",
	cat_mountains_desc: "Climb the highest peaks and explore remote valleys",
	cat_lakes: "Lakes",
	cat_lakes_desc: "Discover crystal-clear alpine lakes and rivers",
	cat_culture: "Cultural Sites",
	cat_culture_desc: "Visit ancient monuments and historical places",
	cat_adventure: "Adventure",
	cat_adventure_desc: "Hiking, camping, and outdoor activities",
	cta_title: "Ready to Explore Tajikistan?",
	cta_desc: "Start planning your journey to discover the natural wonders and cultural treasures of this beautiful country.",
	cta_btn1: "Plan Your Trip",
	cta_btn2: "Learn More",
	nav_home: "Home",
	nav_products: "Tourism Products",
	nav_destinations: "Destinations",
	nav_events: "Events",
	nav_info: "Information",
	nav_contacts: "Contacts",
	footer_about_title: "About Tajikistan Tourism",
	footer_about_desc: "Discover the natural beauty and rich cultural heritage of Tajikistan, a hidden gem in Central Asia.",
	footer_links_title: "Quick Links",
	footer_link_products: "Tourism Products",
	footer_link_guide: "Travel Guide",
	footer_link_events: "Events",
	footer_link_contact: "Contact",
	footer_contact_title: "Contact Info",
	footer_contact_email: "Email: maks88821@gmai.com",
	footer_contact_phone: "Phone: +992919667741",
	footer_contact_address: "Address: Dushanbe, Tajikistan",
	footer_copyright: "© 2024 Tajikistan Tourism. All rights reserved.",
	hero_slider: [
		{
			title: 'TAJIKISTAN',
			subtitle: 'LAND OF',
			description: 'ANCIENT CULTURES',
		},
		{
			title: 'TAJIKISTAN',
			subtitle: 'LAND OF',
			description: 'MAJESTIC MOUNTAINS',
		},
		{
			title: 'TAJIKISTAN',
			subtitle: 'LAND OF',
			description: 'TIMELESS TRADITIONS',
		},
	],
	region_khatlon: "Khatlon",
	region_drs: "DRS",
	region_gbao: "GBAO",
	region_sughd: "Sughd",
	// Login page
	login_page_title: "Login - Tajikistan Tourism",
	login_sign_in: "Sign In",
	login_welcome: "Welcome back! Please sign in to your account",
	login_email: "Email Address",
	login_password: "Password",
	login_remember: "Remember me",
	login_no_account: "Don't have an account?",
	login_sign_up: "Sign Up",
	login_forgot_password: "Forgot Password?",
	// Registration page
	reg_page_title: "Registration - Tajikistan Tourism",
	reg_create_account: "Create Account",
	reg_join_community: "Join our community and discover the beauty of Tajikistan",
	reg_first_name: "First Name",
	reg_last_name: "Last Name",
	reg_email: "Email Address",
	reg_phone: "Phone Number",
	reg_password: "Password",
	reg_confirm_password: "Confirm Password",
	reg_terms_agree: "I agree to the Terms of Service and Privacy Policy",
	reg_terms_service: "Terms of Service",
	reg_privacy_policy: "Privacy Policy",
	reg_newsletter: "Subscribe to our newsletter for travel updates",
	reg_have_account: "Already have an account?",
	reg_sign_in: "Sign In",
	// Contacts page
	contacts_page_title: "Contact Us - Tajikistan",
	contacts_hero_title: "CONTACT US",
	contacts_hero_subtitle: "GET IN",
	contacts_hero_description: "TOUCH",
	contacts_get_touch: "Get in Touch",
	contacts_subtitle: "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
	contacts_info_title: "Contact Information",
	contacts_address: "Address",
	contacts_address_text: "123 Tourism Street\nDushanbe, Tajikistan 734000",
	contacts_phone: "Phone",
	contacts_phone_text: "+992 48 123 4567\n+992 48 123 4568",
	contacts_email: "Email",
	contacts_email_text: "info@tajikistan-tourism.com\nsupport@tajikistan-tourism.com",
	contacts_hours: "Working Hours",
	contacts_hours_text: "Monday - Friday: 9:00 AM - 6:00 PM\nSaturday: 10:00 AM - 4:00 PM\nSunday: Closed",
	contacts_form_title: "Send us a Message",
	contacts_form_name: "Full Name *",
	contacts_form_email: "Email Address *",
	contacts_form_phone: "Phone Number",
	contacts_form_subject: "Subject *",
	contacts_form_select_subject: "Select a subject",
	contacts_form_general: "General Inquiry",
	contacts_form_booking: "Tour Booking",
	contacts_form_support: "Customer Support",
	contacts_form_partnership: "Partnership",
	contacts_form_other: "Other",
	contacts_form_message: "Message *",
	contacts_form_send: "Send Message",
	contacts_find_us: "Find Us",
	contacts_map_subtitle: "Visit our office in the heart of Dushanbe",
	// Auth messages
	auth_passwords_not_match: "Passwords do not match!",
	auth_registration_login_success: "Registration and login successful! Redirecting to main page...",
	auth_registration_success_login_failed: "Registration successful, but login failed. Please log in manually.",
	auth_registration_error: "Registration error",
	auth_connection_error: "Server connection error",
	auth_login_success: "Login successful! Redirecting to main page...",
	auth_authorization_error: "Authorization error",
	// Tourism Products page
	products_page_title: "Tourism Products - Tajikistan",
	products_hero_title: "TOURISM PRODUCTS",
	products_hero_subtitle: "DISCOVER",
	products_hero_description: "UNIQUE EXPERIENCES",
	products_section_title: "Tourism Products",
	products_section_subtitle: "Explore our curated selection of tourism products and experiences",
	products_search_placeholder: "Search by name...",
	products_sort_title_asc: "Alphabetically (A-Z)",
	products_sort_title_desc: "Alphabetically (Z-A)",
	products_sort_difficulty: "By difficulty",
	products_category_all: "All categories",
	products_cta_title: "Ready to Book Your Adventure?",
	products_cta_desc: "Contact our travel experts to customize your perfect Tajikistan experience.",
	products_cta_contact: "Contact Us",
	products_cta_view_all: "View All Products",
	// Products slider
	products_slider: [
		{
			title: 'TOURISM PRODUCTS',
			subtitle: 'DISCOVER',
			description: 'UNIQUE EXPERIENCES',
		},
		{
			title: 'TOURISM PRODUCTS',
			subtitle: 'EXPLORE',
			description: 'AMAZING ADVENTURES',
		},
		{
			title: 'TOURISM PRODUCTS',
			subtitle: 'EXPERIENCE',
			description: 'CULTURAL HERITAGE',
		},
	],
	// Destinations page
	destinations_page_title: "Destinations - Tajikistan",
	destinations_hero_title: "DESTINATIONS",
	destinations_hero_subtitle: "EXPLORE",
	destinations_hero_description: "AMAZING PLACES",
	destinations_section_title: "Popular Destinations",
	destinations_section_subtitle: "Discover the most beautiful and fascinating places in Tajikistan",
	destinations_search_placeholder: "Search by name...",
	destinations_sort_title_asc: "Alphabetically (A-Z)",
	destinations_sort_title_desc: "Alphabetically (Z-A)",
	destinations_sort_region: "By region",
	destinations_region_all: "All regions",
	destinations_cta_title: "Ready to Explore These Amazing Places?",
	destinations_cta_desc: "Start planning your journey to discover the natural wonders and cultural treasures of Tajikistan.",
	destinations_cta_plan: "Plan Your Trip",
	destinations_cta_tours: "View Tours",
	// Destinations slider
	destinations_slider: [
		{
			title: 'DESTINATIONS',
			subtitle: 'EXPLORE',
			description: 'AMAZING PLACES',
		},
		{
			title: 'DESTINATIONS',
			subtitle: 'DISCOVER',
			description: 'HIDDEN GEMS',
		},
		{
			title: 'DESTINATIONS',
			subtitle: 'VISIT',
			description: 'BEAUTIFUL LANDSCAPES',
		},
	],
	// Events page
	events_page_title: "Events - Tajikistan",
	events_hero_title: "EVENTS",
	events_hero_subtitle: "DISCOVER",
	events_hero_description: "CULTURAL FESTIVALS",
	events_section_title: "Upcoming Events",
	events_section_subtitle: "Experience the rich culture and traditions of Tajikistan through our exciting events",
	events_search_placeholder: "Search by name...",
	events_sort_date_desc: "Newest first",
	events_sort_date_asc: "Oldest first",
	events_sort_title_asc: "Alphabetically (A-Z)",
	events_sort_title_desc: "Alphabetically (Z-A)",
	events_location_all: "All locations",
	events_cta_title: "Don't Miss Out on These Amazing Events!",
	events_cta_desc: "Book your tickets early and experience the vibrant culture of Tajikistan.",
	events_cta_contact: "Contact Us",
	events_cta_calendar: "View Calendar",
	// Events slider
	events_slider: [
		{
			title: 'EVENTS',
			subtitle: 'DISCOVER',
			description: 'CULTURAL FESTIVALS',
		},
		{
			title: 'EVENTS',
			subtitle: 'EXPERIENCE',
			description: 'TRADITIONAL CELEBRATIONS',
		},
		{
			title: 'EVENTS',
			subtitle: 'JOIN',
			description: 'EXCITING ACTIVITIES',
		},
	],
	// Information page
	information_page_title: "Information - Tajikistan",
	information_hero_title: "INFORMATION",
	information_hero_subtitle: "ESSENTIAL",
	information_hero_description: "TRAVEL GUIDE",
	information_section_title: "Travel Information",
	information_section_subtitle: "Everything you need to know before visiting Tajikistan",
	// Visa card
	information_visa_title: "Visa Requirements",
	information_visa_desc: "Most visitors need a visa to enter Tajikistan. E-visas are available for many nationalities.",
	information_visa_evisa: "E-visa available for 60+ countries",
	information_visa_processing: "Processing time: 3-5 business days",
	information_visa_valid: "Valid for 45 days",
	information_visa_cost: "Cost: $25-50 USD",
	information_visa_apply: "Apply for Visa",
	// Weather card
	information_weather_title: "Weather & Climate",
	information_weather_desc: "Tajikistan has a continental climate with hot summers and cold winters.",
	information_weather_spring: "Spring (Mar-May): 10-25°C",
	information_weather_summer: "Summer (Jun-Aug): 20-35°C",
	information_weather_autumn: "Autumn (Sep-Nov): 10-25°C",
	information_weather_winter: "Winter (Dec-Feb): -5-10°C",
	information_weather_check: "Check Weather",
	// Currency card
	information_currency_title: "Currency & Money",
	information_currency_desc: "The official currency is the Tajikistani Somoni (TJS).",
	information_currency_rate: "1 USD ≈ 10.5 TJS",
	information_currency_cards: "Credit cards accepted in major cities",
	information_currency_atms: "ATMs available in Dushanbe",
	information_currency_cash: "Cash preferred in rural areas",
	information_currency_converter: "Currency Converter",
	// Transportation card
	information_transport_title: "Transportation",
	information_transport_desc: "Getting around Tajikistan requires planning, especially in remote areas.",
	information_transport_taxis: "Shared taxis between cities",
	information_transport_flights: "Domestic flights available",
	information_transport_public: "Public transport in Dushanbe",
	information_transport_4x4: "4x4 recommended for mountains",
	information_transport_guide: "Transport Guide",
	// Accommodation card
	information_accommodation_title: "Accommodation",
	information_accommodation_desc: "From luxury hotels to homestays, Tajikistan offers various accommodation options.",
	information_accommodation_hotels: "Hotels in major cities",
	information_accommodation_guesthouses: "Guesthouses in rural areas",
	information_accommodation_homestays: "Homestays with locals",
	information_accommodation_camping: "Camping in mountains",
	information_accommodation_book: "Book Accommodation",
	// Food card
	information_food_title: "Food & Cuisine",
	information_food_desc: "Tajik cuisine features hearty dishes with rice, meat, and fresh vegetables.",
	information_food_plov: "Plov (rice with meat)",
	information_food_qurutob: "Qurutob (bread with yogurt)",
	information_food_shashlik: "Shashlik (grilled meat)",
	information_food_fruits: "Fresh fruits and nuts",
	information_food_guide: "Food Guide",
	// Safety section
	information_safety_title: "Safety & Health",
	information_safety_subtitle: "Important information for a safe and healthy trip",
	information_health_title: "Health Information",
	information_health_vaccinations: "No special vaccinations required",
	information_health_water: "Drink bottled or boiled water",
	information_health_medical: "Medical facilities limited in rural areas",
	information_health_insurance: "Travel insurance recommended",
	information_safety_tips_title: "Safety Tips",
	information_safety_embassy: "Register with your embassy",
	information_safety_customs: "Respect local customs and dress modestly",
	information_safety_mountains: "Be cautious in mountain areas",
	information_safety_documents: "Keep copies of important documents",
	// CTA section
	information_cta_title: "Ready to Plan Your Trip?",
	information_cta_desc: "Contact our travel experts for personalized advice and assistance.",
	information_cta_contact: "Contact Us",
	information_cta_tours: "View Tours",
			// Information slider
		information_slider: [
			{
				title: 'INFORMATION',
				subtitle: 'ESSENTIAL',
				description: 'TRAVEL GUIDE',
			},
			{
				title: 'INFORMATION',
				subtitle: 'USEFUL',
				description: 'TRAVEL TIPS',
			},
			{
				title: 'INFORMATION',
				subtitle: 'IMPORTANT',
				description: 'TRAVEL FACTS',
			},
		],
		// Product page
		product_page_title: "Product Details - Tajikistan",
		product_not_found: "Product not found.",
		product_category: "Category:",
		product_duration: "Duration:",
		product_difficulty: "Difficulty:",
		product_contact_booking: "Contact for Booking",
}; 