# Generated by Django 5.2.3 on 2025-07-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
