# Generated by Django 5.2.3 on 2025-07-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tourismproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tourismproduct',
            name='category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tourismproduct',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
