name: Django CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_NAME: mydb
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
      DJANGO_SETTINGS_MODULE: config.settings

    steps:
      - uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Установка зависимостей
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Миграции и тесты
        working-directory: ./backend
        run: |
          sleep 10
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
          python manage.py test
